GET http://localhost:3000/api/products


###
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Rizen 5 3600",
    "price": 3500,
    "categoryId": 3
}

###
GET  http://localhost:3000/api/products/3



###
DELETE http://localhost:3000/api/products/1


###
PUT http://localhost:3000/api/products/1
Content-Type: application/json

{
    "name": "Windows 5 3600",
    "price": 3500,
    "categoryId": 3
}